server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: simpleModule
        uri: lb://simple-service
        predicates:
        - Path=/simple/**


